package com.ufes.automobile.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import androidx.room.Index

/**
 * Represents a displacement record in the local database.
 *
 * This entity stores information about a single journey or movement made by a vehicle.
 * It includes details such as the distance traveled, the date of the displacement,
 * the origin and destination, and a reference to the associated vehicle.
 *
 * @property id The unique identifier for the displacement record. Auto-generated by the database.
 * @property vehicleId The ID of the vehicle that performed the displacement.
 *                    This is a foreign key referencing the `VehicleEntity` table.
 * @property distance The distance traveled during the displacement, in a unit defined by the application (e.g., kilometers, miles).
 * @property date The timestamp representing the date and time of the displacement, typically stored as a Unix timestamp (milliseconds since epoch).
 * @property origin The starting location of the displacement.
 * @property destination The ending location of the displacement.
 *
 * @constructor Creates a new `DisplacementEntity` instance.
 */
@Entity(
    tableName = "displacements",
    foreignKeys = [ForeignKey(
        entity = VehicleEntity::class,
        parentColumns = ["id"],
        childColumns = ["vehicleId"],
        onDelete = ForeignKey.CASCADE
    )],
    indices = [Index(value = ["vehicleId"])]
)
data class DisplacementEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val vehicleId: Int,
    val distance: Float,
    val date: Long,
    val description: String
)
