package com.ufes.automobile.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents an insurance record in the database.
 *
 * This entity stores information about an insurance policy associated with a specific vehicle.
 *
 * @property id The unique identifier for the insurance record. Auto-generated by the database.
 * @property vehicleId The ID of the vehicle this insurance policy is associated with.
 *                     This is a foreign key referencing the `VehicleEntity` table.
 * @property insurer The name of the insurance company.
 * @property policyNumber The policy number assigned by the insurer.
 * @property assistanceDetails Details about the assistance services provided by the insurance policy.
 * @property startDate The start date of the insurance policy as a Unix timestamp (milliseconds).
 * @property endDate The end date of the insurance policy as a Unix timestamp (milliseconds).
 * @property cost The total cost of the insurance policy.
 *
 * @see VehicleEntity
 */
@Entity(
    tableName = "insurance",
    foreignKeys = [ForeignKey(
        entity = VehicleEntity::class,
        parentColumns = ["id"],
        childColumns = ["vehicleId"],
        onDelete = ForeignKey.CASCADE
    )],
    indices = [Index(value = ["vehicleId"])]
)

data class InsuranceEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val vehicleId: Int,
    val insurer: String,
    val policyNumber: String,
    val assistanceDetails: String,
    val startDate: Long,
    val endDate: Long,
    val cost: Float
)